import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import { domAnimation, LazyMotion } from "framer-motion";

import "./global.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
  preload: true,
});

export const metadata: Metadata = {
  title: "eRZet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pl">
      <body className={`${roboto.variable} ${inter.variable} antialiased`}>
        <LazyMotion features={domAnimation}>
          <Header />
          {children}
          <Footer />
        </LazyMotion>
      </body>
    </html>
  );
}
